spring:
  application:
    name: open-game-backend-registry

de:
  opengamebackend:
    application:
      version: @project.version@

server.port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl.defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
